- .travis.yml
- Makefile
- README.md
- appveyor.yml
- wincred/cmd/main_windows.go
- wincred/wincred_windows.go
- wincred/wincred_windows_test.go
> Add support for Windows credential manager.

- Makefile
- appveyor.yml
- osxkeychain/cmd/main_darwin.go
- osxkeychain/osxkeychain_darwin.go
- osxkeychain/osxkeychain_darwin_test.go
- vendor/github.com/danieljoos/wincred/LICENSE
- vendor/github.com/danieljoos/wincred/conversion.go
- vendor/github.com/danieljoos/wincred/native.go
- vendor/github.com/danieljoos/wincred/types.go
- vendor/github.com/danieljoos/wincred/wincred.go
- remove old imports that point to my fork.
- vendor windows dependencies.
- make sure `go test` doesn't try to run tests in the vendor directory.
- sort makefile alphabetically.
> Cleanup imports and vendor dependencies.

- appveyor.yml
> Add matrix to build in different windows platforms.

- .travis.yml
- appveyor.yml
> Add scripts to release tags.

- .travis.yml
- ci/before_deploy.sh
- ci/before_deploy_osx.sh
> Release Linux secret service binary.

- README.md
- credentials/credentials.go
- credentials/credentials_test.go
- credentials/helper.go
- osxkeychain/osxkeychain_darwin.c
- osxkeychain/osxkeychain_darwin.go
- osxkeychain/osxkeychain_darwin.h
- osxkeychain/osxkeychain_darwin_test.go
- secretservice/secretservice_linux.c
- secretservice/secretservice_linux.go
- secretservice/secretservice_linux.h
- secretservice/secretservice_linux_test.go
- wincred/wincred_windows.go
- wincred/wincred_windows_test.go
This matches the implementation for Docker OAuth tokens: https://github.com/docker/docker/pull/20970.
> Move away from password as a name. We store secrets.

- appveyor.yml
> Add a link to the Changelog in each release.

- README.md
- Fix link to project releases
- Fix go command
Signed-off-by: Maxime Gréau <greaumaxime@gmail.com>
> Update related to the move to Docker Organization

- credentials/credentials.go
- credentials/credentials_test.go
- credentials/helper.go
> Export credentials functions to be able to use them as a library.

- osxkeychain/cmd/main_darwin.go
- osxkeychain/osxkeychain_darwin.go
- osxkeychain/osxkeychain_darwin_test.go
- secretservice/cmd/main_linux.go
- secretservice/secretservice_linux.go
- secretservice/secretservice_linux_test.go
- wincred/cmd/main_windows.go
- wincred/wincred_windows.go
- wincred/wincred_windows_test.go
> Publish helper structs and methods.

- MAINTAINERS
> Add maintainers file.

- README.md
- client/client.go
- client/client_test.go
- client/command.go
- credentials/credentials.go
- credentials/error.go
- credentials/helper.go
- osxkeychain/osxkeychain_darwin.go
- osxkeychain/osxkeychain_darwin_test.go
- secretservice/secretservice_linux.go
- secretservice/secretservice_linux_test.go
- wincred/wincred_windows.go
- wincred/wincred_windows_test.go
This is a simplification of how the docker engine implements
this feature, but it will be ported there once this is merged.
> Add client functions to allow integrations within other CLIs.

- osxkeychain/osxkeychain_darwin.go
Signed-off-by: ebriney <emmanuel.briney@docker.com>
> mac: delete credentials before adding them

- CHANGELOG.md
It's been 9months, lot's of fixes, let's release 👼
/cc @runcom @cpuguy83 
Signed-off-by: Vincent Demeester <vincent@sbr.pm>
> Prepare v0.4.0 release

- MAINTAINERS
/cc @jeanlaurent @thaJeztah @icecrime 
🦁
Signed-off-by: Vincent Demeester <vincent@sbr.pm>
> Add n4ss as maintainer 👼

- wincred/wincred_windows.go
Avoiding to get unlabelled credentials
Signed-off-by: Simon Ferquel <simon.ferquel@docker.com>
> [Windows] align get with list behavior

- Makefile
> Update version tag to v0.5.1

- Makefile
- appveyor.yml
Adds a simple AppVeyor build, running vet, go test and expose artifacts
> AppVeyor build

- Makefile
- credentials/credentials.go
- credentials/version.go
This add a simple version switch to the CLI, to help determine which version is currently running.
Release is updated to read the version from sources.
> Add version command

- .travis.yml
> Update TravisCI to use Go 1.7

- Makefile
Add a `winrelease` target, that could be useful when doing release.
> Adding winrelease target

- client/command.go
This change introduce a new entry point for credential helpers. The caller can now pass environment variable so that the credential helper can be aware of them.
The motivation of this feature is that Azure Container Registry is developing a credential helper that wants to know which docker file is currently active. Note that when `docker` command was called with `--config` flag, there is currently no way for docker to pass that information to the credential helper.
This feature will allow changes to be made in docker cli so it could, for example set the `DOCKER_CONFIG` environmental variable before calling the credential helper.
> A new entry point for calling the cred helpers that allow passing environment variables

- CHANGELOG.md
- credentials/version.go
> Bump 0.6.0

- pass/pass_linux.go
See comment for details, but basically, let's actually use pass to check
that it works.
Signed-off-by: Tycho Andersen <tycho@docker.com>
> pass: better initialization check

- CHANGELOG.md
- README.md
> Add instructions for pass helper configuration

- .travis.yml
- appveyor.yml
> fix osxkeychain ci

- wincred/wincred_windows.go
> Fix Windows CI

- pass/pass_linux.go
The exec.Command code and os.Getenv implementation were both needlessly
verbose. This replaces them with simpler variations.
Note, this will conflict with #108, I'd rather that go in first and me rebase this on that.
> pass: simplify some code

- README.md
> Typo fixed.

- credentials/version.go
Signed-off-by: Ulrich VACHON <ulrich.vachon@docker.com>
> Bump version to 0.6.2

- .travis.yml
Looks like this commit was missing on master, and only in the tag
@ulrich @silvin-lubecki ptal
> Merge 'v0.6.2' to master

- credentials/version.go
> Bump to 0.6.3

- osxkeychain/osxkeychain_darwin.go
improves #82
The error doesn't strictly mean that keychain is locked so unlock command may not always help. Eg. binary may be blocked to access keychain item if it has been manually changed but this should cover most of the common cases without confusing the user.
Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>
> osxkeychain: improve error message for non-interactive sessions

- .travis.yml
- pass/pass.go
- registryurl/url_go18.go
- secretservice/secretservice_linux_test.go
taking the first 2 commits from https://github.com/docker/docker-credential-helpers/pull/204
> travis: temporarily disabling ppc64le, and fix some linting issues

- docker-bake.hcl
closes #172
Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>
> support linux/ppc64le and linux/s390x cross build

- .github/CODE_OF_CONDUCT.md
- .github/CONTRIBUTING.md
- .github/SECURITY.md
Looks like these were never added to this repo; adding them inside the `.github` directory to not overly pollute the repository-rood
> Add CONTRIBUTING.md, CODE_OF_CONDUCT.md, SECURITY.md

- .github/workflows/build.yml
Also add ubuntu-22.04 to test matrix.
> ci: bump runners to ubuntu-22.04

- .github/dependabot.yml
- .github/workflows/build.yml
similar to https://github.com/tonistiigi/xx/pull/141
> ci: update github actions to latest stable

- .github/workflows/build.yml
similar to https://github.com/moby/buildkit/pull/4660
> ci: set codecov token

- .github/workflows/build.yml
- Dockerfile
- deb/Dockerfile
> update to go1.23.12
