docker/docker-credential-helpers

client/client.go, client/client_test.go, credentials/credentials.go, credentials/credentials_test.go, credentials/helper.go, osxkeychain/osxkeychain_darwin.go, osxkeychain/osxkeychain_darwin_test.go, secretservice/secretservice_linux.go, secretservice/secretservice_linux_test.go, wincred/wincred_windows.go, wincred/wincred_windows_test.go
[]string, []string -> map[string]string because the other APIs assume a
1:1 correspondence
Signed-off-by: Jake Sanders <jsand@google.com>
=> Implement client.List, change list API

vendor/github.com/danieljoos/wincred/conversion.go, vendor/github.com/danieljoos/wincred/native.go, vendor/github.com/danieljoos/wincred/wincred.go, wincred/wincred_windows.go
This PR updates the vendor pkg `wincred`:
- Removed need for `C` package (danieljoos/wincred@8d753fac3f8cec5374df7f303ba40237de62333e)
- Added some null-checks (addresses #21 - danieljoos/wincred@1c80202994708d42f05003601a4914ead119bf42)
- `List` returns an empty list instead of an error if no credentials are installed on the system (danieljoos/wincred@fd3b27f99d1b6b46c9a70e41d376bfff63af235f)
Other than that, it fixes the Windows build (`make wincred`) by removing two lines in `wincred_windows.go` that seem to be a leftover of the last merge #25 .
=> Updated wincred vendor & fixed Windows build

osxkeychain/osxkeychain_darwin.go
Signed-off-by: Emmanuel Briney <emmanuel.briney@docker.com>
=> Add cgo flags to support older version of OSX (10.10, 10.11)

osxkeychain/osxkeychain_darwin.c
- rewrite keychain_list to get right server urls with port instead of just path
- fix some memory leaks
Signed-off-by: Emmanuel Briney <emmanuel.briney@docker.com>
=> Reconstruct the full url when doing `keychain_list`

Makefile
- This allow the binary to be codesigned
- This is a specific target, if you build locally you can still use `osxkeychain` as usual.
- You need to have the cert installed on your building machine for the codesign to work
=> Add a makefile target to codesign output binary on macOS

secretservice/secretservice_linux_test.go
The logic behind this PR's purpose and implementation can be found here: https://github.com/docker/docker-credential-helpers/issues/48
This PR needs the following PR to work properly: https://github.com/docker/docker-credential-helpers/pull/49 which fixes the broken `secureservice` implementation.
=> Fix secretservice tests and expected behaviors

Makefile
- `mkdir -p` with only a subdir is not useful
- it creates a `-p` directory in windows cmd
=> Remove mkdir -p where neccessary

wincred/wincred_windows.go, wincred/wincred_windows_test.go
I'm sorry, I failed to commit all my changes it seems in the following PR: https://github.com/docker/docker-credential-helpers/pull/49
Main issue to be solved is still: https://github.com/docker/docker/issues/31517 . Now all platforms seem to be working well.
This commit fixes the Windows build as well as the tests for this platform.
=> Fix syntax typos and tests implementation for Windows

.gitignore, Makefile
- Add a clean phase to the `Makefile` that take care of removing the `bin` and `release` directory.
- make sure we clean and run test before a osxrelease
=> Clean and run test before osx release

client/command.go
As part of our design for Azure Docker Registry, we found that it would be useful (necessary for us) for cred manager to pipe it's stderr back to cli client. Hence this PR.
=> Caller of cred helpers would now see the stderr returns from cred helpers

secretservice/secretservice_linux.go
This adds a workaround for the `secretservice` sub-package to build under 32bit Linux.
It limits the total number of list entries to 2^28!
Tested it to compile successfully under Debian jessie 32bit with golang 1.6.2.
Fixes #57
=> Workaround for Linux 32-bit build

.travis.yml
To match the version used in docker
ping @n4ss @vdemeester PTAL
=> Update TravisCI to use Go 1.8

credentials/credentials_test.go, credentials/error.go, osxkeychain/osxkeychain_darwin.go, osxkeychain/osxkeychain_darwin_test.go, osxkeychain/url_go18.go, osxkeychain/url_non_go18.go, wincred/wincred_windows_test.go
If secrets are stored without specifying a scheme
(https://), the keychain-helper would interpret the
hostname as _path_, causing lookup of secrets to fail.
This patch makes sure that a scheme is added (if missing).
If no scheme is specified, https:// is used as a default.
=> Fix storing URLs without scheme

pass/pass_linux.go
This way clients don't have to run their own checks, they can just use the
library's detection.
Signed-off-by: Tycho Andersen <tycho@docker.com>
=> pass backend: expose pass initialized flag

pass/pass_linux.go, pass/pass_linux_test.go
It turns out the cred helpers protocol is to return "" and not an error
when a credential isn't present, so let's do that.
Signed-off-by: Tycho Andersen <tycho@docker.com>
=> return "" instead of an error when pass isn't present

Makefile
Address some issues with the Makefile
* mkdir fails when `bin` exists
* getting golint fails if previously installed w/out the `-u` flag
=> Fix Makefile issues

pass/pass_linux.go
This also fixes the following issues:
1. Safe for concurrent initialization still (it was before in 'init',
but the alternative to this PR is not)
2. Uses the same password directory during init as it does during
runtime (the change to getPassDir in initialization logic.
3. Prints significantly better errors if initialization fails
4. Has slightly cleaner abstractions by hiding the initialization check
in 'runPass'
The 4th item there does mean there are a few cases where more work is
done before erroring, but that amount of work is trivial and my manual
audit didn't reveal anything that seemed worrying.
Fixes #96, alternative to #106 
cc @vdemeester; I'm sorry if this steps on your toes at all. I started implementing this independently when running `img` (which depends on this) pulled up …
=> pass: only init on run, and do so lazily

secretservice/secretservice_linux.go
Fixes #23, #103, #104 
Signed-off-by: Jake Sanders jsand@google.com
=> C.free(unsafe.Pointer(err)) -> C.g_error_free(err)

pass/pass_linux.go
Changed the way that `docker-credential-helpers` check if `password-store` is initialized.
The current way inserts and removes a password, each time it is called, to make sure that pass is initialized.
This creates a lot of commits if the password-store is made as a git repository (which is quite awful).
The following is how many commits has been made, over a span of ~2 months...
```
$ git log | grep 'docker-pass-initialized-check' | wc -l
1430
```
I have changed the way to just do a `pass ls`, as it will fail if pass is not initialized.
If it should fail, it will fail at a read of pass or insert of pass anyways, and therefore this solution is much more elegant.
=> pass: changed the way for checking if password-store is initalized

.travis.yml, Makefile, credentials/version.go, osxkeychain/osxkeychain_darwin.go
Using the new public key for RVM, update to golang 1.9.1 version…
Signed-off-by: Ulrich VACHON <ulrich.vachon@docker.com>
=> Fix Travis configuration, update XCode version, Golang version and set to minimum macOS version to 10.11.

osxkeychain/osxkeychain_darwin.go
Currently, `docker-credential-osxkeychain list` returns an error if the keychain entry is missing.
However, `docker logout` actually clears the `Docker Credentials` keychain entry. Meaning that after performing the logout, the calls to `docker-credential-osxkeychain list` returns an error.
When building images (at least with `docker-compose build`, did not try directly with `docker build`) calls to `docker-credential-osxkeychain list` are performed, resulting in build failure as the credential helpers returns a non-0 return code.
This is probably not the expected behaviour. Also, this is not the case on windows, as the used implementation from `danieljoos/wincred` correctly handles the case:
``` go
func List() ([]*Credential, error) {
creds, err := nativeCredEnumerate("", true)
if err != …
```
=> Fix docker-credential-osxkeychain list behaviour in case of missing entry in keychain

.travis.yml
Adding power support in travis.yml
- Adding ppc64le build and running "before_script_linux.sh" on intel only via travis.yml
Signed-off-by: ghatwala <ghatwala@us.ibm.com>
=> Attempt to build this package on power

Jenkinsfile
Update the Windows Authenticode code signing certificate and password to the new one that is valid until 2021-10-01.
I've added it as new credential in Jenkins, so we can easily migrate (or rollback) per repo or release branch.
=> [DESKTOP-1469] Update Windows Authenticode certificate

secretservice/secretservice_linux.go
List wraps the error from secretservice_linux.c so the List can give the caller more useful error message for diagnosing.
Signed-off-by: Qi Wang <qiwan@redhat.com>
=> List wraps the error from secretservice_linux.c.

secretservice/secretservice_linux.go
In case of error, return nil for expected map along with error
Signed-off-by: Alakesh Haloi <alakeshh@amazon.com>
=> Fix return values in List() in secretservice_linux.go

.github/workflows/build.yml, Dockerfile, README.md, docker-bake.hcl
follow-up https://github.com/docker/docker-credential-helpers/pull/209
Tests run on specific runners with respect to the target OS and the results are merged and sent to Codecov. Containerized tests are only available for host platform atm (that's why a specific job has been added in the build workflow).
cc @thaJeztah
=> Test stage and ci jobs

.github/workflows/build.yml, Dockerfile, Makefile, docker-bake.hcl
=> vendor validation

Dockerfile, Makefile
There's no need to specify the file to build, as we're building the "main" packages as a whole.
=> simplify "go build" commands

README.md
- closes https://github.com/docker/docker-credential-helpers/pull/134
- closes https://github.com/docker/docker-credential-helpers/pull/167
- closes https://github.com/docker/docker-credential-helpers/pull/200
=> Update local build instructions in README

Dockerfile, Makefile, pass/pass.go
Pass is described as "The Standard Unix Password Manager", and so it can
easily run on more than just Linux. Namely, it's supported on macOS. The
CLI is identical to the Linux build, which means the Linux helper code
for Pass is fully applicable toward the macOS build - a couple of
renames being the only needed thing, purely for semantic correctness.
Resolves https://github.com/docker/docker-credential-helpers/issues/146
=> Allow pass helper to be built for macOS

Makefile
https://github.com/docker/docker-credential-helpers/pull/232#issuecomment-1226943341
Fixes #232
=> Use relative paths in Makefile for "go build"

.dockerignore, .github/workflows/build.yml, .gitignore, Dockerfile, Makefile, credentials/credentials.go, credentials/version.go, deb/Dockerfile, deb/build-deb, deb/debian/rules
Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>
=> Set version and revision at linked time

pass/pass.go, pass/pass_test.go
fixes https://github.com/docker/docker-credential-helpers/issues/220
=> pass: return an error when a cred doesn't exist

.github/workflows/build.yml, Dockerfile, pass/pass_test.go
follow-up https://github.com/docker/docker-credential-helpers/pull/237#issuecomment-1230324172
using musl to build dynamically linked secretservice helper is not suitable so switch to debian based as it is for current released binaries.
Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>
=> Dockerfile: debian based build

credentials/credentials_test.go, osxkeychain/osxkeychain_darwin.go, pass/pass.go, secretservice/secretservice_linux.go, secretservice/secretservice_linux_test.go, wincred/wincred_windows.go
Doing a one-pass of formatting the code with gofumpt, which provides a superset of gofmt.
=> format code with gofumpt

osxkeychain/osxkeychain_darwin.go, osxkeychain/osxkeychain_darwin_test.go
This allows a Delete for non-existing credentials to be handled.
=> osxkeychain: Delete(): return typed errors

client/client_test.go, credentials/credentials_test.go, osxkeychain/osxkeychain_darwin_test.go, registryurl/parse_test.go, wincred/wincred_windows_test.go
See individual commits for details
=> rewrite tests to use sub-tests, improve error-handling in tests, and use t.Cleanup()

client/client.go, client/client_test.go, client/command.go, credentials/credentials.go
See individual commits for details. Some outlined below:
Don't set Env if not set; the default is already handled if it's nil; from
the documentation: https://pkg.go.dev/os/exec@go1.20.4#Cmd.Env
// If Env is nil, the new process uses the current process's
// environment.
Use `os/exec/Cmd.Environ()` instead of `os.Environ()`, which was added in
go1.19, and handles additional environment variables, such as `PWD` on POSIX
systems, and `SYSTEMROOT` on Windows. https://pkg.go.dev/os/exec@go1.20.4#Cmd.Environ
Also remove a redundant `fmt.Sprintf()`, as we're only concatenating strings.
GNU guidelines describes; https://www.gnu.org/prep/standards/html_node/_002d_002dversion.html#g_t_002d_002dversion
The program’s name should be a constant string; don’t compute it from argv[0].
The idea is to …
=> Assorted improvements, and add  "--version, -v", and "--help, -h" flags

Dockerfile, Makefile, osxkeychain/osxkeychain_darwin.go
partially solves #280 
`xx` sets a minimal macos version if not set through `MACOSX_VERSION_MIN` env var: https://github.com/tonistiigi/xx/blob/3d00d096c8bf894ec29bae5caa5aea81d9c187a5/base/xx-info#L203-L209
=> osxkeychain: match min macos version for xx

README.md
fixes https://github.com/docker/docker-credential-helpers/issues/260
Adds instruction to install emulators to be able to build with Docker. We don't encounter this issue on Docker Desktop as emulators are already installed. On CI we already install emulators with qemu action: https://github.com/docker/docker-credential-helpers/blob/bdd92dd0d34762226ed61e31e940a22fc03ed801/.github/workflows/build.yml#L137-L139
=> readme: install emulators when building with docker

pass/pass.go
- relates to https://github.com/docker/docker-credential-helpers/pull/109
commit a13ff500176e7570239691424050fb46b0a7f05b (https://github.com/docker/docker-credential-helpers/pull/109) simplified the handling of env-vars in getPassDir(), but moved interpolation of env-vars to the end of the function.
As a result, a custom path passed through `$PASSWORD_STORE_DIR` would now be interpolated, instead of taken as-is. For example;
PASSWORD_STORE_DIR=$PWD/world
Would now interpolate `$PWD`, instead of using a literal `$PWD`.
This patch changes the logic to only expand env-vars for the default location.
Use stdlib's `os.UserHomeDir()` instead of depending only on `$HOME`. Note that
this does not yet does nss lookups for situations where `$HOME` / `$USERPROFILE`
is not set.
=> pass: fix interpolation of $PASSWORD_STORE_DIR, and use os.UserHomeDir()

credentials/error.go
This allows for checking the error-type returned to be matched with the errdefs utilities.
=> credentials: improve errors and error-handling

client/client_test.go, credentials/credentials_test.go, osxkeychain/osxkeychain_test.go, pass/pass_test.go, registryurl/parse_test.go, secretservice/secretservice_test.go
updates all tests, except for wincreds (handled in https://github.com/docker/docker-credential-helpers/pull/274)
=> use designated domains in tests (RFC2606) (step 1)

client/client.go, credentials/error.go
some changes I had stashed locally 🤷 😂
=> move trimming whitespace to error-check helpers

pass/pass.go, pass/pass_test.go
commit 2fc2313bb1a9608195bb2a7624983b52901d4c73 changed the errors returned by the pass credentials-helper to use a errCredentialsNotFound. This error string is used in the client to distinguish a "not found" error from other errors. (see [client.Get][1]).
However, there were additional second code-paths that returned a custom error, which would not be detected as a "not found" error, resulting in an error when logging out;
Removing login credentials for https://index.docker.io/v1/
WARNING: could not erase credentials:
https://index.docker.io/v1/: error erasing credentials - err: exit status 1, out: `error getting credentials - err: exit status 1, out: `no usernames for https://index.docker.io/v1/``
This patch:
- updates Pass.Get() to return a errCredentialsNotFound if no credentials were …
=> pass: return correct error, and ignore empty stores on list

pass/pass.go, pass/pass_test.go
While the implementation of these is fairly trivial, we want them to remain the same. This patch adds utilities to handle the encoding and decoding of the server-URLs.
**- How I did it**
**- How to verify it**
=> pass: add utilities for encoding/decoding serverURL

pass/pass.go
listPassdir already handles "not found" errors, in which case it returns an [empty result][1]. Previously this would return a custom error, but since 1bb9aa321022b0fcf5b484fe2fc12d9cef1f4b6e (https://github.com/docker/docker-credential-helpers/pull/321), an empty result produces a `errCredentialsNotFound`, making this check redundant.
This patch removes the redundant check.
[1]: https://github.com/docker/docker-credential-helpers/blob/f64d6b131b3da07a6337dc63a882e08ce541d1c1/pass/pass.go#L118-L125
=> pass: Get: remove redundant stat

Dockerfile
bullseye EOL since 14 August 2024: https://www.debian.org/News/2024/20240814
I guess some cross packages have been moved to archive repo, hence why it fails in https://github.com/docker/docker-credential-helpers/pull/338#issuecomment-2436263677
=> dockerfile: update debian to bookworm

client/command.go
Both NewShellProgramFunc and NewShellProgramFuncWithEnv were using createProgramCmdRedirectErr under the hood, but NewShellProgramFunc had an extra indirection through NewShellProgramFuncWithEnv.
Make both a direct wrapper for createProgramCmdRedirectErr instead.
=> client: remove some indirection and touch-up GoDoc

.github/workflows/build.yml
=> ci: update bake-action to v6

secretservice/secretservice.c, secretservice/secretservice.go, secretservice/secretservice.h
- rebase / carry of https://github.com/docker/docker-credential-helpers/pull/207
- supersedes / closes https://github.com/docker/docker-credential-helpers/pull/207
Secretservice entries have a "label". This is intended to be a human-readable description. It's actually called "Description" in UIs like seahorse, and the listing of existing secrets shows this as a name for each one.
The entries stored by the credential helper set this to simply the repository URL. This is rather unfriendly, since entries like "gitlab.com" and "index.docker.io/v1" show up. Mixed in with entries from all other applications, it's hard to figure out what application owns each entry.
This commit changes the label used when saving entries to be something human-readable (this is the intent of the "label" field, …
=> Set a better displaylabel for secretservice

secretservice/secretservice.c
fixes #336
`secret_item_get_secret()` may return null if an item is locked or not loaded. While we set `SECRET_SEARCH_LOAD_SECRETS` and `SECRET_SEARCH_UNLOCK`, there may still be locked items, for example the user may refuse the unlock request.
So we still need to check if the secret data is NULL before we can try to reference it.
=> secretservice: fix null derefence on locked collections

go.mod, go.sum, vendor/github.com/danieljoos/wincred/sys_unsupported.go, vendor/golang.org/x/sys/windows/aliases.go, vendor/golang.org/x/sys/windows/empty.s, vendor/golang.org/x/sys/windows/env_windows.go, vendor/golang.org/x/sys/windows/syscall_windows.go, vendor/golang.org/x/sys/windows/types_windows.go, vendor/golang.org/x/sys/windows/zsyscall_windows.go, vendor/modules.txt
- Bump golang.org/x/sys from 0.17.0 to 0.20.0
- Bump github.com/stretchr/testify from 1.8.4 to 1.9.0
- Added missing constant to sys_unsupported.go to avoid breaking builds on non-Windows platforms.
full diff: https://github.com/danieljoos/wincred/compare/v1.2.1...v1.2.2
=> vendor:  github.com/danieljoos/wincred v1.2.2

.github/workflows/build.yml, Dockerfile, Makefile, deb/Dockerfile, docker-bake.hcl
Compiling with Go >= 1.22 on arm/v6 is failing with the following error
message:
27.84 gcc_libinit.c:44:8: error: large atomic operation may incur significant performance penalty; the access size (4 bytes) exceeds the max lock-free size (0  bytes) [-Werror,-Watomic-alignment]
For these Go versions, we need to manually link to libatomic as arm/v6
does not support atomic intrinsics and neither the CGo, nor the C
toolchain automatically link to that library.
go1.22.11 (released 2025-01-16) includes security fixes to the crypto/x509 and
net/http packages, as well as bug fixes to the runtime. See the Go 1.22.11
milestone on our issue tracker for details.
- https://github.com/golang/go/issues?q=milestone%3AGo1.22.11+label%3ACherryPickApproved
- full diff: …
=> update to go1.23.6

osxkeychain/osxkeychain.go
**osxkeychain: list: do not error out when keychain is empty**
Commit https://github.com/docker/docker-credential-helpers/commit/4cdcdc29eb662eace1ec682ed7d70c99f4c00649 replaced the in-tree Objective-C code with github.com/keybase/go-keychain and inadvertently introduced a new failure mode on the `List` operation - it now fails when the keychain is empty.
Before:
```
$ ./bin/build/docker-credential-osxkeychain list
{}
```
After:
```
$ ./bin/build/docker-credential-osxkeychain list
credentials not found in native keychain
```
**osxkeychain: store: use Apple's proto consts**
Commit https://github.com/docker/docker-credential-helpers/commit/4cdcdc29eb662eace1ec682ed7d70c99f4c00649 swapped consts `kSecProtocolTypeHTTPS` and `kSecProtocolTypeHTTP` with plain-text "https" and …
=> [v0.9.0] osxkeychain: fix regressions on get and list

go.mod
Commit 4cdcdc2 introduced two regressions in the `osxkeychain` credential helper,  on `list` and `get` operations. These were addressed in:
- Commit c7514a0: osxkeychain: list: do not error out when keychain is empty
- Commit f4cdabf: osxkeychain: store: use Apple's proto consts
=> go.mod: retract v0.9.0

osxkeychain/osxkeychain.go, osxkeychain/osxkeychain_test.go
Commit 4cdcdc2 changed the format of `list` output. Before that commit, the json keys were containing full URIs (`scheme://host/path[:port]`), but afterward, the keys were only containing the path component.
With this commit, the `list` operation now returns full URIs (fixing the regression), and also fixes the malformed URIs issue when a port is specified (introduced by 19ec1c3, and affecting >=v0.4.2,<v0.9.0).
**- How to verify it**
`TestOSXKeychainHelper` has been improved to check which `ServerURL`s are returned by `list`.
CI should be green.
```
- osxkeychain: list: return full URIs (regression introduced in v0.9.0)
- osxkeychain: list: fix malformed URIs when a `ServerURL` is stored with a port specified (introduced in v0.4.2)
```
=> osxkeychain: list: return full server URIs

go.mod
`osxkeychain` in v0.9.1 still doesn't list credentials as prior versionsdid. We're retracting this version too.
=> go.mod: retract v0.9.1

osxkeychain/osxkeychain.go
Prior to v0.9.0, the osxkeychain creds helper was adding the `atyp` attribute (ie. authentication type) to its credentials. It was also specifying this attribute when querying the keychain for credentials.
Since v0.9.0, we don't set this attribute anymore. So, if a credential is stored with v0.9.0+ and then queried with a v0.8.2 helper, the atyp attribute will be missing and the credential won't be found.
**- How to verify it**
```
- osxkeychain: fix a bug that was preventing credentials created with v0.9.0+ to be retrieved with older versions
```
=> osxkeychain: store: add atyp attribute

Dockerfile
don't need extra stages per target os.
Signed-off-by: CrazyMax <crazy-max@users.noreply.github.com>
=> Dockerfile: merge build stages

go.mod, go.sum, vendor/github.com/danieljoos/wincred/conversion.go, vendor/github.com/danieljoos/wincred/sys.go, vendor/modules.txt
fix unsafe uintptr usage to be GC-safe on go1.25
full diff: https://github.com/danieljoos/wincred/compare/v1.2.2...v1.2.3
=> vendor: github.com/danieljoos/wincred v1.2.3

.github/workflows/build.yml, Dockerfile, deb/Dockerfile
=> update to go1.25.1
